### ISSUE TITLE
Implement ECS-Compatibility Mode

### ISSUE THREAD

**Issue by yaauie** [logstash-plugins/logstash-integration-kafka#17]
_This is a stub issue, and needs to be fleshed out with details specific to
this plugin._

***

As a part of the effort to make plugins able to run in an ECS-Compatible manner
by default in an upcoming release of Logstash, this plugin needs to either
implement an ECS-Compatibility mode or certify that it does not implicitly use
fields that conflict with ECS.

**Comment by kares** [comment]
Kafka output uses the plain codec to encode events and does not introduce any extra fields.

Kafka input also relies on the plain codec by default and uses `@metadata`  to store meta information such as topic (`[@metadata][kafka][topic]`) information and/or headers (e.g. `[@metadata][kafka][headers][user-id]`) :heavy_check_mark: 

However, in case the `schema_registry_url => ...` is used the plugin parses the "decoded message" and [parses it as a JSON object, setting raw field values](https://github.com/logstash-plugins/logstash-integration-kafka/blob/v10.8.1/lib/logstash/inputs/kafka.rb#L352-L356). As an improvement (for ECS) it would make sense to try using the JSON codec as a default (instead of plain) when the registry url is set to potentially leverage the codec's target support ?
